ALTER TABLE health_risk_alerts ADD COLUMN category VARCHAR(40) DEFAULT 'General';
UPDATE health_risk_alerts SET category = 'General' WHERE category IS NULL;

CREATE TABLE plan_access_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_user_id BIGINT NOT NULL,
    client_code VARCHAR(40),
    client_name VARCHAR(120),
    advisor_user_id BIGINT NOT NULL,
    advisor_name VARCHAR(120),
    resource_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    responded_at TIMESTAMP,
    responded_by_user_id BIGINT,
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_par_client FOREIGN KEY (client_user_id) REFERENCES users(id),
    CONSTRAINT fk_par_advisor FOREIGN KEY (advisor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_par_lookup ON plan_access_requests(advisor_user_id, client_user_id, resource_type);
CREATE INDEX idx_par_resource_status ON plan_access_requests(resource_type, status);
