CREATE TABLE medical_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_user_id BIGINT NOT NULL,
    client_code VARCHAR(40),
    client_name VARCHAR(120),
    medical_advisor_id BIGINT NOT NULL,
    advisor_name VARCHAR(120),
    reason VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    rejection_reason VARCHAR(500),
    requested_at TIMESTAMP NOT NULL,
    responded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mrq_client FOREIGN KEY (client_user_id) REFERENCES users(id),
    CONSTRAINT fk_mrq_advisor FOREIGN KEY (medical_advisor_id) REFERENCES users(id)
);

CREATE INDEX idx_mrq_client ON medical_requests(client_user_id, requested_at);
CREATE INDEX idx_mrq_advisor_status ON medical_requests(medical_advisor_id, status);
