CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_user_id BIGINT NOT NULL,
    balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wallets_client UNIQUE (client_user_id),
    CONSTRAINT fk_wallets_client FOREIGN KEY (client_user_id) REFERENCES users(id)
);

CREATE TABLE wallet_topup_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(40) NOT NULL,
    client_user_id BIGINT NOT NULL,
    client_code VARCHAR(40),
    client_name VARCHAR(120),
    wallet_id BIGINT NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    note VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    rejection_reason VARCHAR(500),
    receipt_stored_name VARCHAR(180),
    receipt_original_name VARCHAR(180),
    receipt_content_type VARCHAR(80),
    receipt_size BIGINT,
    receipt_uploaded_at TIMESTAMP,
    receipt_uploaded_by BIGINT,
    approved_by BIGINT,
    approved_by_name VARCHAR(120),
    approved_at TIMESTAMP,
    rejected_by BIGINT,
    rejected_by_name VARCHAR(120),
    rejected_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_topup_request_number UNIQUE (request_number),
    CONSTRAINT fk_topup_client FOREIGN KEY (client_user_id) REFERENCES users(id),
    CONSTRAINT fk_topup_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id)
);

CREATE TABLE wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    payment_id VARCHAR(40),
    top_up_request_id BIGINT,
    type VARCHAR(20) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    description VARCHAR(200) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    reference VARCHAR(40) NOT NULL,
    balance_after DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wtx_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id),
    CONSTRAINT fk_wtx_topup FOREIGN KEY (top_up_request_id) REFERENCES wallet_topup_requests(id)
);

CREATE INDEX idx_topup_client ON wallet_topup_requests(client_user_id, created_at);
CREATE INDEX idx_topup_status ON wallet_topup_requests(status, created_at);
CREATE INDEX idx_wtx_wallet ON wallet_transactions(wallet_id, created_at);
