CREATE TABLE wellness_centres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wellness_centres_name UNIQUE (name)
);

ALTER TABLE users ADD COLUMN wellness_centre_id BIGINT;
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP;

ALTER TABLE users ADD CONSTRAINT fk_users_wellness_centre
    FOREIGN KEY (wellness_centre_id) REFERENCES wellness_centres (id);

CREATE INDEX idx_users_wellness_centre ON users (wellness_centre_id);
CREATE INDEX idx_users_created_at ON users (created_at);
CREATE INDEX idx_users_last_login_at ON users (last_login_at);
