-- Medical Advisor CRUD: discrete medical history entries + safety validations + soft-delete support

CREATE TABLE medical_history_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    client_code VARCHAR(40),
    client_name VARCHAR(120),
    record_type VARCHAR(40) NOT NULL,
    condition_name VARCHAR(200),
    allergy_info VARCHAR(500),
    description VARCHAR(2000),
    severity VARCHAR(40),
    recorded_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Active',
    created_by_user_id BIGINT,
    created_by_name VARCHAR(120),
    deactivated_at TIMESTAMP,
    deactivated_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mhe_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_mhe_user ON medical_history_entries(user_id);
CREATE INDEX idx_mhe_status ON medical_history_entries(status);
CREATE INDEX idx_mhe_client_code ON medical_history_entries(client_code);

CREATE TABLE safety_validations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    client_code VARCHAR(40),
    client_name VARCHAR(120),
    reference_type VARCHAR(40),
    reference_id VARCHAR(80),
    result_status VARCHAR(40) NOT NULL,
    warnings_json CLOB,
    advisor_notes VARCHAR(2000),
    validated_by_user_id BIGINT,
    validated_by_name VARCHAR(120),
    validated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sv_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_sv_user ON safety_validations(user_id);
CREATE INDEX idx_sv_result ON safety_validations(result_status);

ALTER TABLE health_profiles ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE health_profiles ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE health_profiles ADD COLUMN deleted_by_user_id BIGINT;

ALTER TABLE health_risk_alerts ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE health_risk_alerts ADD COLUMN deleted_at TIMESTAMP;
