-- Right-to-erasure workflow (admin hard delete after soft delete)

CREATE TABLE erasure_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type VARCHAR(40) NOT NULL,
    record_id BIGINT NOT NULL,
    client_user_id BIGINT NOT NULL,
    legal_basis VARCHAR(500) NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_by_user_id BIGINT NOT NULL,
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by_user_id BIGINT,
    reviewed_at TIMESTAMP,
    review_notes VARCHAR(2000),
    executed_by_user_id BIGINT,
    executed_at TIMESTAMP,
    CONSTRAINT fk_erasure_client FOREIGN KEY (client_user_id) REFERENCES users(id),
    CONSTRAINT fk_erasure_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_erasure_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_erasure_executed_by FOREIGN KEY (executed_by_user_id) REFERENCES users(id)
);

CREATE INDEX idx_erasure_status ON erasure_requests(status);
CREATE INDEX idx_erasure_record ON erasure_requests(record_type, record_id);
CREATE INDEX idx_erasure_client ON erasure_requests(client_user_id);
