import Badge from './Badge'

const statusMap = {
  active: { label: 'Active', tone: 'green' },
  completed: { label: 'Completed', tone: 'teal' },
  upcoming: { label: 'Upcoming', tone: 'teal' },
  cancelled: { label: 'Cancelled', tone: 'gray' },
  confirmed: { label: 'Confirmed', tone: 'green' },
  open: { label: 'Open', tone: 'amber' },
  'in progress': { label: 'In Progress', tone: 'teal' },
  'pending reply': { label: 'Pending Reply', tone: 'amber' },
  resolved: { label: 'Resolved', tone: 'green' },
  monitoring: { label: 'Monitoring', tone: 'amber' },
  followup: { label: 'Follow-up', tone: 'amber' },
  'follow-up': { label: 'Follow-up', tone: 'amber' },
  unread: { label: 'New', tone: 'green' },
  read: { label: 'Read', tone: 'gray' },
  current: { label: 'Current', tone: 'green' },
  previous: { label: 'Previous', tone: 'gray' },
  paused: { label: 'Paused', tone: 'amber' },
  'up to date': { label: 'Up to date', tone: 'green' },
  draft: { label: 'Draft', tone: 'gray' },
  inactive: { label: 'Inactive', tone: 'gray' },
  scheduled: { label: 'Scheduled', tone: 'teal' },
  available: { label: 'Available', tone: 'green' },
  'in session': { label: 'In Session', tone: 'teal' },
  unavailable: { label: 'Unavailable', tone: 'gray' },
  break: { label: 'Break', tone: 'amber' },
  pending: { label: 'Pending', tone: 'amber' },
  withdrawn: { label: 'Withdrawn', tone: 'gray' },
  'needs review': { label: 'Needs Review', tone: 'amber' },
  'update due': { label: 'Update Due', tone: 'amber' },
  'on track': { label: 'On Track', tone: 'green' },
  'plan completed': { label: 'Plan Completed', tone: 'teal' },
  expired: { label: 'Expired', tone: 'gray' },
  approved: { label: 'Approved', tone: 'green' },
  'review required': { label: 'Review Required', tone: 'amber' },
  beginner: { label: 'Beginner', tone: 'teal' },
  intermediate: { label: 'Intermediate', tone: 'green' },
  advanced: { label: 'Advanced', tone: 'amber' },
  due: { label: 'Due', tone: 'amber' },
  'review due': { label: 'Review Due', tone: 'amber' },
  'needs follow-up': { label: 'Needs Follow-up', tone: 'amber' },
  archived: { label: 'Archived', tone: 'gray' },
  'medical allergy': { label: 'Medical Allergy', tone: 'amber' },
  'dietary restriction': { label: 'Dietary Restriction', tone: 'teal' },
  'food intolerance': { label: 'Food Intolerance', tone: 'teal' },
  preference: { label: 'Preference', tone: 'green' },
  'under review': { label: 'Under Review', tone: 'amber' },
  'pending review': { label: 'Pending Review', tone: 'amber' },
  reviewed: { label: 'Reviewed', tone: 'green' },
  'follow-up required': { label: 'Follow-up Required', tone: 'amber' },
  moderate: { label: 'Moderate', tone: 'amber' },
  low: { label: 'Low', tone: 'teal' },
  medium: { label: 'Medium', tone: 'teal' },
  high: { label: 'High', tone: 'amber' },
  urgent: { label: 'Urgent', tone: 'amber' },
  'update required': { label: 'Update Required', tone: 'amber' },
  shared: { label: 'Shared', tone: 'teal' },
  assigned: { label: 'Assigned', tone: 'teal' },
  'pending client reply': { label: 'Pending Client Reply', tone: 'amber' },
  escalated: { label: 'Escalated', tone: 'amber' },
  closed: { label: 'Closed', tone: 'gray' },
  normal: { label: 'Normal', tone: 'teal' },
  complaint: { label: 'Complaint', tone: 'amber' },
  suggestion: { label: 'Suggestion', tone: 'teal' },
  'positive feedback': { label: 'Positive Feedback', tone: 'green' },
  acknowledged: { label: 'Acknowledged', tone: 'teal' },
  new: { label: 'New', tone: 'green' },
  responded: { label: 'Responded', tone: 'teal' },
  unassigned: { label: 'Unassigned', tone: 'amber' },
  successful: { label: 'Successful', tone: 'green' },
  operational: { label: 'Operational', tone: 'green' },
  connected: { label: 'Connected', tone: 'green' },
  'attention required': { label: 'Attention Required', tone: 'amber' },
  locked: { label: 'Locked', tone: 'amber' },
  suspended: { label: 'Suspended', tone: 'amber' },
}

export default function StatusBadge({ status, className = '' }) {
  const key = String(status || '').toLowerCase()
  const mapped = statusMap[key] || {
    label: status || 'Unknown',
    tone: 'gray',
  }

  return (
    <Badge tone={mapped.tone} className={className}>
      {mapped.label}
    </Badge>
  )
}
